### ISSUE TITLE
Error on DataFrame display of TensorArray with non-numeric values for Pandas 1.0.x

### ISSUE THREAD

**Issue by BryanCutler** [CODAIT/text-extensions-for-pandas#135]
After the fix in #133  the GenericArrayFormatter which pandas uses to format strings to display a DataFrame can not handle a TensorArray with dims > 1 and raises an error when printing for Pandas versions 1.0.x. This has been fixed in Pandas 1.1.x, but a suitable workaround for Pandas 1.0.x has not been found. Instead of using a TensorArray, users should make a column lists of objects, if required to work with this version of Pandas.

**Comment by frreiss** [comment]
@BryanCutler is this problem fixed/worked-around now?

**Comment by BryanCutler** [comment]
Yes, the fix from #172 would apply to this as well
