### ISSUE TITLE
Prepare release version 0.1b2 

### ISSUE THREAD

**Issue by BryanCutler** [CODAIT/text-extensions-for-pandas#159]
With #157 merged, we should make a release of version 0.1b2. This will also allow us to get starting with the process of making a conda package available.

**Comment by BryanCutler** [comment]
@frreiss is there anything else you would like to get in before we make this release? I could try make it and upload to PyPI, are there some steps written down someplace or is the process pretty straightforward?

**Comment by frreiss** [comment]
@BryanCutler thanks for stepping up on this task! I don't have any outstanding changes at the moment, so publishing a 0.1b2 release off of the current master branch is good. I've documented the release process [here](https://github.com/CODAIT/text-extensions-for-pandas/blob/master/docs/release.md). Note that the API doc generation currently produces many warnings, so step 5 is a bit aspirational at this point.

**Comment by BryanCutler** [comment]
Quick update:
I ran into a TensorArray issue with one of the notebooks, and am trying to get it worked out. I won't be available tomorrow, so will try to get this done by end of week.

**Comment by BryanCutler** [comment]
PR with notebook fix: https://github.com/CODAIT/text-extensions-for-pandas/pull/165

**Comment by BryanCutler** [comment]
Release is done now, uploaded to PyPI. I'm currently working on getting a conda package going.
