### ISSUE TITLE
bert align_bert_tokens_to_corpus_tokens fails with Pandas 1.2.0

### ISSUE THREAD

**Issue by BryanCutler** [CODAIT/text-extensions-for-pandas#163]
bert.align_bert_tokens_to_corpus_tokens() fails with Pandas 1.2.0 due to the error described here:

https://github.com/CODAIT/text-extensions-for-pandas/pull/157#issuecomment-754313463

**Comment by frreiss** [comment]
Note: We currently have a workaround in place for this problem, but the workaround involves monkey-patching parts of Pandas' `__repr__`.

**Comment by BryanCutler** [comment]
This was actually due to an error aggregation on extension arrays which I fixed upstream at https://github.com/pandas-dev/pandas/pull/38982 and is in v1.2.1. We can close this now.
