### ISSUE TITLE
Enable automatic running of regression tests on new pull requests

### ISSUE THREAD

**Issue by frreiss** [CODAIT/text-extensions-for-pandas#33]
Create a `.travis.yml` file that configures CI for the repository.

Set up this file to trigger the following actions on the Travis build server for each pull request:
1. Create a suitable Python environment for running our regression tests (see `env.sh`)
1. Activate the Python environment
1. Run our regression tests (`python -m unittest discover` from the root of the repository) 

Make a pull request to the put the file in place.

Make a second test pull request that deliberately breaks a regression test to ensure that the CI is working after the first PR is merged.

**Comment by frreiss** [comment]
See the [getting started guide](https://travis-ci.org/getting_started) for a walkthrough.

**Comment by frreiss** [comment]
Note: It would be best to push the `.travis.yml` file to your own personal fork of the the repository and make sure that everything is working ok before working with the admins of this project to put the config file into the root of the master branch.

**Comment by ZachEichen** [comment]
I think this is complete. I think we could probably close it.
