### ISSUE TITLE
Factor out Gremlin code

### ISSUE THREAD

**Issue by frreiss** [CODAIT/text-extensions-for-pandas#60]
- [x] Move all the code under `text_extensions_for_pandas/gremlin` to a new project.

- [x] Remove all references to Gremlin from the `text-extensions-for-pandas` project's `README.md` file.

- [ ] Add enough regression testing to the new project that we can tell whether the Gremlin engine is completely broken by an upstream change from Text Extensions for Pandas.

- [x] Move the current version of the notebook `Watson_NLU_Demo.ipynb` to the new project to serve as a demo for Gremlin-related functionality.

- [x] Replace the portions of `Watson_NLU_Demo.ipynb` that depend on our Gremlin engine with code that doesn't depend on that engine. My recommendation is to pull out the region of each sentence between two sides of a relationship that Watson NLU found, then display the portion of the SpaCy parse tree that covers that part of the sentence.

- [ ] Write a README.md file for the new project, explaining that this project holds an experimental embedded Gremlin query processing engine built on top of Pandas and Text Extensions for Pandas, and that the aim of this engine is to support declarative processing of NLP-related graphs such as parse trees and relationship graphs.

**Comment by frreiss** [comment]
New project created at https://github.com/CODAIT/embedded_gremlin

**Comment by BryanCutler** [comment]
Renamed new repo slightly to use dash like text extensions: https://github.com/CODAIT/embedded-gremlin

**Comment by BryanCutler** [comment]
@frreiss I'm trying to get Travis CI going on the gremlin repo. I added the `.travis.yml` file and tried to activate it with my travis account, but I think I don't have the right repo permissions. Could you please check to see if you can activate it?

**Comment by BryanCutler** [comment]
PR to remove Gremlin from text extensions at #65
