### ISSUE TITLE
Implement all required hooks for ExtensionArray types

### ISSUE THREAD

**Issue by frreiss** [CODAIT/text-extensions-for-pandas#62]
Implement [all required hooks](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.api.extensions.ExtensionArray.html) for ExtensionArray types.

In particular, the regression tests that Pandas ships with for ensuring correctness of ExtensionArrays should pass.

Also, extend our own regression suite so that it runs the Pandas tests in addition to our low-level tests.

**Comment by frreiss** [comment]
#71 is related to this issue.

**Comment by BryanCutler** [comment]
#69 adds tests for TensorArray

#77 updates tests for Pandas 1.1.x

**Comment by frreiss** [comment]
I think we've implemented enough of this API to mark this issue as closed.
