### ISSUE TITLE
Fix TokenSpanArray.__hash__

### ISSUE THREAD

**Issue by BryanCutler** [CODAIT/text-extensions-for-pandas#90]
Currently falls back to CharSpanArray.__hash__, which fails.

Test failing: TestPandasMethods.test_not_hashable

**Comment by frreiss** [comment]
The key requirement here is that the `__equals__` methods of all our span types consider two spans to be equal if they cover the same character range of the same string. That notion of equality is the most intuitive I've been able to come up with, though I'm open to alternatives.

The implementations of `__hash__` need to be consistent with the notion of equality implemented in `__equals__`, or Python and Pandas operations that rely on hash tables will behave strangely. As long as equality is defined as "begin, end and text are the same", the hash functions for `TokenSpan`, `CharSpan`, `TokenSpanArray`, and `CharSpanArray` all need to be based only on those three attributes.

**Comment by frreiss** [comment]
N.B. #27  is also relevant to this issue.

**Comment by frreiss** [comment]
This problem appears to be fixed now, as part of 1ec4880.
