### ISSUE TITLE
Create BaseSpanArray class as common subclass to CharSpanArray and TokenSpanArray

### ISSUE THREAD

**Issue by BryanCutler** [CODAIT/text-extensions-for-pandas#91]
Currently, TokenSpanArray is derived from CharSpanArray, but is not a proper instance of a CharSpanArray and is missing certain attributes. For example the test for TokenSpanArray in TestPandasMethods.test_equals fails because it uses the CharSpanArray.equals method and does not have attributes like `_equivalent_arrays`.

It would make the class structure clearer if common functionality was moved to an abstract BaseSpanArray class and specific functionality implemented in the concrete classes.

**Comment by BryanCutler** [comment]
@frreiss what do you think about this?

**Comment by frreiss** [comment]
The short answer is that originally `TokenSpanArray` and `CharSpanArray` were completely separate classes, and that design caused a lot of problems. Many operations that could take either type as input ended up with special-case code to handle both array types. There was also quite a bit of redundant functionality between the two classes. On several occasions, subtle differences in this redundant code led to nasty bugs.

Making `CharSpanArray` the superclass simplified the code a lot. Several complex methods, such `contains()`, `equals()` and `overlaps()`, only need to be implemented in `CharSpanArray`. Operations under `text_extensions_for_pandas.spanner` that only require begin and end offsets can be implemented for `CharSpanArray` and will just work if passed a `TokenSpanArray`.

That said, I'd be open to an alternative class structure if you can figure out how to retain the code-simplification benefits of the current arrangement. Maybe a superclass with opaque versions of most of the functionality of `CharSpanArray` but none of the data fields?

**Comment by BryanCutler** [comment]
Ok, I'll try out some things and open a PR for discussion if it seems to be better.
