### ISSUE TITLE
Expose the contents of `io` as multiple sub-packages

### ISSUE THREAD

**Issue by frreiss** [CODAIT/text-extensions-for-pandas#97]
Currently, all the public functions under `text_extensions_for_pandas.io` are exposed in the top-level package of the project. This portion of the namespace is getting crowded, and some of the names are becoming confusing. For example, it's not clear from the name of the `make_tokens_and_features()` function that the function is part of the SpaCy integration.

We should expose the functions under `io` as a hierarchy of functions, not a flat collection. I recommend using the current location within the source tree to define the hierarchy. For example, `tp.make_tokens_and_features()` would become `tp.io.spacy.make_tokens_and_features()`.

FYI @BryanCutler

**Comment by BryanCutler** [comment]
+1, having a hierarchy will make it clear what it is being used for.

**Comment by frreiss** [comment]
Closed by #119
